### ISSUE TITLE
A PanicException when load newick tree file

### ISSUE THREAD

**Issue by CNwangbin** [aaronmussig/PhyloDM#15] opened 2023-06-16 08:48 UTC
The error occured when using 
`PhyloDM.load_from_newick_path(tree_path)`  to load a newick tree file. 
The error message is
`thread '<unnamed>' panicked at 'Taxon already exists in the tree: 'Taxon("0.999")'', src/pdm.rs:98:9
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
---------------------------------------------------------------------------
PanicException                            Traceback (most recent call last)
/home/wangbin/phy2vec/matrix_factorization.py in ()
     [20](file:///home/wangbin/phy2vec/matrix_factorization.py?line=19)     np.savetxt(save_mat_name, embedding, delimiter="\t", fmt="%.4f")
     [21](file:///home/wangbin/phy2vec/matrix_factorization.py?line=20)     np.savetxt(save_labels_name, labels, delimiter="\t", fmt="%s")
---> [23](file:///home/wangbin/phy2vec/matrix_factorization.py?line=22) embed_tree('data/tree.nwk', 200, 'data')

/home/wangbin/phy2vec/matrix_factorization.py in embed_tree(tree_path, n_dims, output_path)
      [7](file:///home/wangbin/phy2vec/matrix_factorization.py?line=6) def embed_tree(tree_path, n_dims, output_path):
      [8](file:///home/wangbin/phy2vec/matrix_factorization.py?line=7)     # read tree file, format:newick
----> [9](file:///home/wangbin/phy2vec/matrix_factorization.py?line=8)     pdm = PhyloDM.load_from_newick_path(tree_path)
     [10](file:///home/wangbin/phy2vec/matrix_factorization.py?line=9)     # obtain pairwise distance matrix and labels
     [11](file:///home/wangbin/phy2vec/matrix_factorization.py?line=10)     mat = pdm.dm(norm=False)

File [~/.local/lib/python3.9/site-packages/phylodm/__init__.py:27](https://vscode-remote+ssh-002dremote-002b172-002e16-002e100-002e108.vscode-resource.vscode-cdn.net/home/wangbin/phy2vec/~/.local/lib/python3.9/site-packages/phylodm/__init__.py:27), in PhyloDM.load_from_newick_path(cls, path)
     [21](file:///home/wangbin/.local/lib/python3.9/site-packages/phylodm/__init__.py?line=20) """Load a tree from a Newick file.
     [22](file:///home/wangbin/.local/lib/python3.9/site-packages/phylodm/__init__.py?line=21) 
     [23](file:///home/wangbin/.local/lib/python3.9/site-packages/phylodm/__init__.py?line=22) Args:
     [24](file:///home/wangbin/.local/lib/python3.9/site-packages/phylodm/__init__.py?line=23)     path: The path to the Newick file.
     [25](file:///home/wangbin/.local/lib/python3.9/site-packages/phylodm/__init__.py?line=24) """
     [26](file:///home/wangbin/.local/lib/python3.9/site-packages/phylodm/__init__.py?line=25) pdm = cls()
---> [27](file:///home/wangbin/.local/lib/python3.9/site-packages/phylodm/__init__.py?line=26) pdm._rs.load_from_newick_path(path=path)
     [28](file:///home/wangbin/.local/lib/python3.9/site-packages/phylodm/__init__.py?line=27) return pdm

PanicException: Taxon already exists in the tree: 'Taxon("0.999")'`

**Comment by CNwangbin** [comment] 2023-06-16 08:49
For cleared display, the whole error message is.
`thread '<unnamed>' panicked at 'Taxon already exists in the tree: 'Taxon("0.999")'', src/pdm.rs:98:9
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
---------------------------------------------------------------------------
PanicException                            Traceback (most recent call last)
/home/wangbin/phy2vec/matrix_factorization.py in ()
     [20](file:///home/wangbin/phy2vec/matrix_factorization.py?line=19)     np.savetxt(save_mat_name, embedding, delimiter="\t", fmt="%.4f")
     [21](file:///home/wangbin/phy2vec/matrix_factorization.py?line=20)     np.savetxt(save_labels_name, labels, delimiter="\t", fmt="%s")
---> [23](file:///home/wangbin/phy2vec/matrix_factorization.py?line=22) embed_tree('data/tree.nwk', 200, 'data')

/home/wangbin/phy2vec/matrix_factorization.py in embed_tree(tree_path, n_dims, output_path)
      [7](file:///home/wangbin/phy2vec/matrix_factorization.py?line=6) def embed_tree(tree_path, n_dims, output_path):
      [8](file:///home/wangbin/phy2vec/matrix_factorization.py?line=7)     # read tree file, format:newick
----> [9](file:///home/wangbin/phy2vec/matrix_factorization.py?line=8)     pdm = PhyloDM.load_from_newick_path(tree_path)
     [10](file:///home/wangbin/phy2vec/matrix_factorization.py?line=9)     # obtain pairwise distance matrix and labels
     [11](file:///home/wangbin/phy2vec/matrix_factorization.py?line=10)     mat = pdm.dm(norm=False)

File [~/.local/lib/python3.9/site-packages/phylodm/__init__.py:27](https://vscode-remote+ssh-002dremote-002b172-002e16-002e100-002e108.vscode-resource.vscode-cdn.net/home/wangbin/phy2vec/~/.local/lib/python3.9/site-packages/phylodm/__init__.py:27), in PhyloDM.load_from_newick_path(cls, path)
     [21](file:///home/wangbin/.local/lib/python3.9/site-packages/phylodm/__init__.py?line=20) """Load a tree from a Newick file.
     [22](file:///home/wangbin/.local/lib/python3.9/site-packages/phylodm/__init__.py?line=21) 
     [23](file:///home/wangbin/.local/lib/python3.9/site-packages/phylodm/__init__.py?line=22) Args:
     [24](file:///home/wangbin/.local/lib/python3.9/site-packages/phylodm/__init__.py?line=23)     path: The path to the Newick file.
     [25](file:///home/wangbin/.local/lib/python3.9/site-packages/phylodm/__init__.py?line=24) """
     [26](file:///home/wangbin/.local/lib/python3.9/site-packages/phylodm/__init__.py?line=25) pdm = cls()
---> [27](file:///home/wangbin/.local/lib/python3.9/site-packages/phylodm/__init__.py?line=26) pdm._rs.load_from_newick_path(path=path)
     [28](file:///home/wangbin/.local/lib/python3.9/site-packages/phylodm/__init__.py?line=27) return pdm

PanicException: Taxon already exists in the tree: 'Taxon("0.999")'`

**Comment by aaronmussig** [comment] 2023-06-17 03:57
Thanks for raising this issue. It seems that the `light_phylogeny` crate that Rust uses to parse the Newick file doesn't support the extended Newick format. I've created a new release (3.0.0) that will fall back to DendroPy if Rust is unable to load from a Newick file.

My assumption is that this is the case for your tree. Although this might not be the case, if you are able to provide your Newick file then I can try debug a bit further.

**Comment by CNwangbin** [comment] 2023-06-19 01:22
Thanks for your reply. I will send the file to to your email [aaronmussig@gmail.com](mailto:aaronmussig@gmail.com).

**Comment by aaronmussig** [comment] 2023-06-19 03:01
Thanks for sending the tree through. I confirmed it is fixed with v3.0.0.

It will be a little bit slower ~40 seconds extra because it needs to use DendroPy to load the tree. The distance matrix calculation will still be the same performance, I will work on fixing this in a future release, but at least a workaround exists.

**Comment by CNwangbin** [comment] 2023-06-19 03:07
Thanks, I would like to know the approximate time of your upcoming release. Alternatively, could you provide me with an example code solution now?

**Comment by aaronmussig** [comment] 2023-06-19 03:17
You can upgrade the package by running `python -m pip install -U phylodm`

No need to change your code, it should work as is.

**Comment by CNwangbin** [comment] 2023-06-19 03:18
Thanks. I will try do it.

**Comment by CNwangbin** [comment] 2023-06-19 03:50
Thanks. This actually helped me to fixed this bug.

**Closed as completed** 2023-06-19 03:50 UTC
Labels: bug
